pipeline {

    agent any

    environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhubaccount')
        ANSIBLE_PRIVATE_KEY=credentials('ansible-prod-pk')
    }

    stages {
        
        stage("Build"){

            steps {
                withMaven(maven: 'maven'){
                    sh 'mvn spring-javaformat:apply'
                    sh 'mvn clean compile -DskipTests'
                    sh 'mvn package -DskipTests'
                }
            }          
        }

         stage("Testing"){

            steps{
                withMaven(maven: 'maven'){
                    sh 'mvn -Dtest=src\test\java\org\springframework\samples\petclinic\PetClinicIntegrationTests.java test'
                }
            }
        }

        stage("Create Docker image and push to DockerHub"){

            steps{

                sh 'docker build -t dogfail/petclinic-app:latest .'      
            
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'

                sh 'docker push dogfail/petclinic-app:latest'
                }
            
        }
       
        stage("Deploy"){

            steps{
                sh 'ansible-playbook -i inventory.ini --private-key=$ANSIBLE_PRIVATE_KEY ansible-playbook.yml'
            }
        }
    }
}